# Generated by Django 6.0.1 on 2026-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_rename_prix_vente_produit_prix_vente_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_vente_detail',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
