# Generated by Django 6.0.1 on 2026-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='recu_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recu_vente/'),
        ),
    ]
